### ISSUE TITLE
(defun info (url)) overwrites the builtin info reader

### ISSUE THREAD

**Issue by ArneBab** [4hiziri/rocket-chat#2]
The function info in rocket-chat-api.el overwrites the builtin info reader (M-x info or C-h i). Could you prefix the API functions (i.e. with rc-)? Or does this only happen because I manually ran eval-buffer in rocket-chat.api?

**Comment by 4hiziri** [comment]
I added rcapi to info as prefix and fixed this problem.
Thanks.

**Comment by ArneBab** [comment]
Thank you!
